apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-main-account-jet
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-argocd-demo
      name: aws-main-account-creds
      key: credentials
---
apiVersion: aws.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-main-account
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-argocd-demo
      name: aws-main-account-creds
      key: credentials
