apiVersion: aws.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: aws-main-account
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-argocd-demo
      name: aws-main-account-creds
      key: credentials
