apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: asghttp.demo.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  group: demo.io
  names:
    kind: ASGHTTP
    plural: asghttp
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                  html:
                    type: string
                  vpcId:
                    type: string
                required:
                - vpcId
                - region
                - html
            required:
            - parameters
          status:
            type: object
            properties:
              tgArn:
                description: ARN for the ALB target group
                type: string
              asgArn:
                description: ARN for the ASG
                type: string
