apiVersion: v2
name: crossplane-infra
description: A Helm chart for a basic Crossplane 
type: application
version: 0.1.0
dependencies:
  - name: crossplane
    version: "1.9.0"
    repository: "https://charts.crossplane.io/stable"
