apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: static-site
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  patchSets:
  - name: region
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
  - name: name
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.name
  - name: site-label
    patches:
    - fromFieldPath: metadata.name
      toFieldPath: metadata.labels.site
      transforms:
      - type: string
        string:
          fmt: "%s"
  writeConnectionSecretsToNamespace: crossplane-argocd-demo
  compositeTypeRef:
    apiVersion: demo.io/v1alpha1
    kind: ASGHTTP
  resources:
  - name: launch-template
    base:
      apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
      kind: LaunchTemplate
      spec:
        forProvider:
          imageId: 'ami-0a1ee2fb28fe05df3'
          instanceType: t2.micro
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.launchTemplateId
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
    - fromFieldPath: spec.parameters.html
      toFieldPath: spec.forProvider.userData
      transforms:
      - type: string
        string:
          fmt: |
            yum update -y
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            echo "%s" > /var/www/html/index.html
      - type: string
        string:
          type: Convert
          convert: ToBase64
  - name: autoscaling-group
    base:
      apiVersion: autoscaling.aws.jet.crossplane.io/v1alpha2
      kind: AutoscalingGroup
      spec:
        forProvider:
          launchTemplate: []
          vpcZoneIdentifier: []
          minSize: 1
          maxSize: 3
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - fromFieldPath: status.launchTemplateId
      toFieldPath: spec.forProvider.launchTemplate[0].name
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.asgName
    - fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.availabilityZones[0]
      transforms:
        - type: string
          string:
            fmt: "%sa"
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
  - name: target-group
    base:
      apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
      kind: LBTargetGroup
      spec:
        forProvider:
          protocol: HTTP
          port: 80
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.arn
      toFieldPath: status.tgArn
    - fromFieldPath: spec.parameters.vpcId
      toFieldPath: spec.forProvider.vpcId
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
  - name: target-group-attachment
    base:
      apiVersion: autoscaling.aws.jet.crossplane.io/v1alpha2
      kind: Attachment
      spec:
        forProvider: {}
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - fromFieldPath: status.tgArn
      toFieldPath: spec.forProvider.albTargetGroupArn
    - fromFieldPath: status.asgName
      toFieldPath: spec.forProvider.autoscalingGroupName
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
  - name: alb-security-group
    base:
      apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
      kind: SecurityGroup
      spec:
        forProvider:
          ingress:
            - protocol: HTTP
              toPort: 80
              cidrBlocks: '0.0.0.0/0'
              ipv6CidrBlocks: '::/0'
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.id
      toFieldPath: status.albSgId
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
  - name: alb
    base:
      apiVersion: elbv2.aws.jet.crossplane.io/v1alpha2
      kind: LB
      spec:
        forProvider:
          enableDeletionProtection: false
          securityGroups: []
          accessLogs:
          - enabled: false
        providerConfigRef:
          name: 'aws-main-account'
    patches:
    - fromFieldPath: spec.parameters.lbSubnets
      toFieldPath: spec.forProvider.subnets
    - fromFieldPath: status.albSgId
      toFieldPath: spec.forProvider.securityGroups[0]
    - type: PatchSet
      patchSetName: region
    - type: PatchSet
      patchSetName: name
    - type: PatchSet
      patchSetName: site-label
