apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: yoyo
    server: "https://kubernetes.cluster.svc"
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps
    targetRevision: HEAD
